config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :competitions
  resources :fencers
  resources :referees
  resources :poules
  resources :matches
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
# frozen_string_literal: true

class Competition < ApplicationRecord
  CATEGORIES = %w[u11 u13 u15 u17 u20 u23 abs vet]
  GENDERS = %w[male female other mix]

  has_and_belongs_to_many :fencers
  has_and_belongs_to_many :referees
  has_many :poules

  validates_presence_of :name, :date, :gender
  validates :gender, inclusion: { in: GENDERS, message: 'Gender not valid' }
  validates :category, inclusion: { in: CATEGORIES, message: 'category not valid' }, allow_nil: true
end

app/models/fencer.rb
# frozen_string_literal: true

class Fencer < ApplicationRecord
  GENDERS = %w[male female other]

  has_and_belongs_to_many :competitions
  has_many :matches

  validates_presence_of :first_name
  validates :gender, inclusion: { in: GENDERS, message: 'Gender not valid' }
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  belongs_to :poule, optional: true

  belongs_to :right_fencer, class_name: 'Fencer', foreign_key: :right_fencer_id
  belongs_to :left_fencer, class_name: 'Fencer', foreign_key: :left_fencer_id
end

app/models/poule.rb
# frozen_string_literal: true

class Poule < ApplicationRecord
  belongs_to :competition
  belongs_to :referee, optional: true

  has_many :matches

  validates_presence_of :number, :piste
end

app/models/referee.rb
# frozen_string_literal: true

class Referee < ApplicationRecord
  has_and_belongs_to_many :competitions
  has_many :poules

  validates_presence_of :first_name
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/competitions_controller.rb
# frozen_string_literal: true

class CompetitionsController < ApplicationController
  def index
    @competitions = Competition.all
  end

  def show
    @competition = Competition.find(params[:id])
  end

  def new
    @competition = Competition.new
  end

  def create
    @competition = Competition.create(safe_params)

    if @competition.save
      redirect_to @competition
    else
      render :new
    end
  end

  def edit
    @competition = Competition.find(params[:id])
  end

  def update
    @competition = Competition.find(params[:id])

    if @competition.update(safe_params)
      redirect_to @competition
    else
      render :edit
    end
  end

  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    redirect_to competitions_path
  end

  private

  def safe_params
    params.require(:competition).permit(:name, :category, :location, :date, :gender, :category)
  end
end

app/controllers/fencers_controller.rb
# frozen_string_literal: true

class FencersController < ApplicationController
  def index
    @fencers = Fencer.all
  end

  def show
    @fencer = Fencer.find(params[:id])
  end

  def new
    @fencer = Fencer.new
  end

  def create
    @fencer = Fencer.create(safe_params)

    if @fencer.save
      redirect_to @fencer
    else
      render :new
    end
  end

  def edit
    @fencer = Fencer.find(params[:id])
  end

  def update
    @fencer = Fencer.find(params[:id])

    if @fencer.update(safe_params)
      redirect_to @fencer
    else
      render :edit
    end
  end

  def destroy
    @fencer = Fencer.find(params[:id])
    @fencer.destroy

    redirect_to fencers_path
  end

  private

  def safe_params
    params.require(:fencer).permit(:first_name, :last_name, :birthday, :country, :gender)
  end
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new
  end

  def create
    # TODO: Add select of right and left fencers
    @match = Match.create(safe_params.merge({
      right_fencer: Fencer.first,
      left_fencer: Fencer.last
    }))

    if @match.save
      redirect_to @match
    else
      render :new
    end
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])

    if @match.update(safe_params)
      redirect_to @match
    else
      render :edit
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    redirect_to matches_path
  end

  private

  def safe_params
    params.require(:match).permit(:left_points, :right_points, :priority)
  end
end

app/controllers/poules_controller.rb
# frozen_string_literal: true

class PoulesController < ApplicationController
  def index
    @poules = Poule.all
  end

  def show
    @poule = Poule.find(params[:id])
  end

  def new
    @poule = Poule.new
  end

  def create
    #TODO Change competition to select
    @poule = Poule.create(safe_params.merge(competition: Competition.first))

    if @poule.save
      redirect_to @poule
    else
      render :new
    end
  end

  def edit
    @poule = Poule.find(params[:id])
  end

  def update
    @poule = Poule.find(params[:id])

    if @poule.update(safe_params)
      redirect_to @poule
    else
      render :edit
    end
  end

  def destroy
    @poule = Poule.find(params[:id])
    @poule.destroy

    redirect_to poules_path
  end

  private

  def safe_params
    params.require(:poule).permit(:number, :piste)
  end
end

app/controllers/referees_controller.rb
# frozen_string_literal: true

class RefereesController < ApplicationController
  def index
    @referees = Referee.all
  end

  def show
    @referee = Referee.find(params[:id])
  end

  def new
    @referee = Referee.new
  end

  def create
    @referee = Referee.create(safe_params)

    if @referee.save
      redirect_to @referee
    else
      render :new
    end
  end

  def edit
    @referee = Referee.find(params[:id])
  end

  def update
    @referee = Referee.find(params[:id])

    if @referee.update(safe_params)
      redirect_to @referee
    else
      render :edit
    end
  end

  def destroy
    @referee = Referee.find(params[:id])
    @referee.destroy

    redirect_to referees_path
  end

  private

  def safe_params
    params.require(:referee).permit(:first_name, :last_name, :birthday, :country, :gender)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/competitions/_form.html.erb
<%= form_with model: competition do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.date_select :date, required: true %>
  </div>

  <div>
    <%= form.label :gender %>
    <%= form.select :gender, options_for_select(Competition::GENDERS, competition.gender), required: true %>
  </div>

  <div>
    <%= form.label :category %>
    <%= form.select :category, options_for_select(Competition::CATEGORIES, competition.category) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1> <%=@competition.name %> </h1>

<%= render 'form', competition: @competition %>

app/views/competitions/index.html.erb
<h1> Competitions </h1>

<ul>
  <% @competitions.each do |competition| %>
    <li>
      <%= link_to competition.name, competition %>
      <%= link_to "Edit", edit_competition_path(competition) %>
      <%= link_to "Destroy", competition_path(competition),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/competitions/new.html.erb
<h1> New competition </h1>

<%= render 'form', competition: @competition %>

app/views/competitions/show.html.erb
<%= link_to "Competitions", competitions_path %>

<h1> <%= @competition.name%> </h1>

<ul>
  <li> ID: <%= @competition.id %> </li>
  <li> name: <%= @competition.name %> </li>
  <li> location: <%= @competition.location %> </li>
  <li> date: <%= @competition.date %> </li>
  <li> gender: <%= @competition.gender %> </li>
  <li> category: <%= @competition.category %> </li>
</ul>

<ul>
  <li> <%= link_to "Edit", edit_competition_path(@competition) %> </li>
  <li> <%= link_to "Destroy", competition_path(@competition),
    method: :delete,
    data: { confirm: 'Are you sure?' } %> </li>
</ul>

app/views/fencers/_form.html.erb
<%= form_with model: fencer do |form| %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name, required: true %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div>
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :gender %>
    <%= form.select :gender, options_for_select(Fencer::GENDERS, fencer.gender), required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fencers/edit.html.erb
<h1> <%=@fencer.first_name %> </h1>

<%= render 'form', fencer: @fencer %>

app/views/fencers/index.html.erb
<h1> Fencers </h1>

<ul>
  <% @fencers.each do |fencer| %>
    <li>
      <%= link_to "#{fencer.first_name} #{fencer.last_name}", fencer %>
      <%= link_to "Edit", edit_fencer_path(fencer) %>
      <%= link_to "Destroy", fencer_path(fencer),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/fencers/new.html.erb
<h1> New Fencer </h1>

<%= render 'form', fencer: @fencer %>

app/views/fencers/show.html.erb
<%= link_to "Fencers", fencers_path %>

<h1> <%= @fencer.first_name%> <%= @fencer.last_name%></h1>

<ul>
  <li> ID: <%= @fencer.id %> </li>
  <li> first_name: <%= @fencer.first_name %> </li>
  <li> last_name: <%= @fencer.last_name %> </li>
  <li> birthday: <%= @fencer.birthday %> </li>
  <li> gender: <%= @fencer.gender %> </li>
  <li> country: <%= @fencer.country %> </li>
</ul>

<ul>
  <li> <%= link_to "Edit", edit_fencer_path(@fencer) %> </li>
  <li> <%= link_to "Destroy", fencer_path(@fencer),
    method: :delete,
    data: { confirm: 'Are you sure?' } %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FTO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with model: match do |form| %>
  <div>
    <%= form.label :right_points %>
    <%= form.number_field :right_points , required: true %>
  </div>

  <div>
    <%= form.label :left_points %>
    <%= form.number_field :left_points , required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1> <%=@match.id %> </h1>

<%= render 'form', match: @match %>

app/views/matches/index.html.erb
<h1> Matches </h1>

<ul>
  <% @matches.each do |match| %>
    <li>
      <%= link_to match.id, match %>
      <%= link_to "Edit", edit_match_path(match) %>
      <%= link_to "Destroy", match_path(match),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/matches/new.html.erb
<h1> New match </h1>

<%= render 'form', match: @match %>

app/views/matches/show.html.erb
<%= link_to "Matches", matches_path %>

<ul>
  <li> ID: <%= @match.id %> </li>
  <li> right_points: <%= @match.right_points %> </li>
  <li> left_points: <%= @match.left_points %> </li>
</ul>

<ul>
  <li> <%= link_to "Edit", edit_match_path(@match) %> </li>
  <li> <%= link_to "Destroy", match_path(@match),
    method: :delete,
    data: { confirm: 'Are you sure?' } %> </li>
</ul>

app/views/poules/_form.html.erb
<%= form_with model: poule do |form| %>
  <div>
    <%= form.label :number %>
    <%= form.number_field :number, required: true %>
  </div>

  <div>
    <%= form.label :piste %>
    <%= form.number_field :piste, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/poules/edit.html.erb
<h1> <%=@poule.number %> </h1>

<%= render 'form', poule: @poule %>

app/views/poules/index.html.erb
<h1> Poules </h1>

<ul>
  <% @poules.each do |poule| %>
    <li>
      <%= link_to poule.number, poule %>
      <%= link_to "Edit", edit_poule_path(poule) %>
      <%= link_to "Destroy", poule_path(poule),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/poules/new.html.erb
<h1> New poule </h1>

<%= render 'form', poule: @poule %>

app/views/poules/show.html.erb
<%= link_to "Poules", poules_path %>

<h1> <%= @poule.number %> </h1>

<ul>
  <li> ID: <%= @poule.id %> </li>
  <li> number: <%= @poule.number %> </li>
  <li> piste: <%= @poule.piste %> </li>
</ul>

<ul>
  <li> <%= link_to "Edit", edit_poule_path(@poule) %> </li>
  <li> <%= link_to "Destroy", poule_path(@poule),
    method: :delete,
    data: { confirm: 'Are you sure?' } %> </li>
</ul>

app/views/referees/_form.html.erb
<%= form_with model: referee do |form| %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name, required: true %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/referees/edit.html.erb
<h1> <%=@referee.first_name %> </h1>

<%= render 'form', referee: @referee %>

app/views/referees/index.html.erb
<h1> Referees </h1>

<ul>
  <% @referees.each do |referee| %>
    <li>
      <%= link_to "#{referee.first_name} #{referee.last_name}", referee %>
      <%= link_to "Edit", edit_referee_path(referee) %>
      <%= link_to "Destroy", referee_path(referee),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/referees/new.html.erb
<h1> New Referee </h1>

<%= render 'form', referee: @referee %>

app/views/referees/show.html.erb
<%= link_to "Referee", referees_path %>

<h1> <%= @referee.first_name%> <%= @referee.last_name%></h1>

<ul>
  <li> ID: <%= @referee.id %> </li>
  <li> first_name: <%= @referee.first_name %> </li>
  <li> last_name: <%= @referee.last_name %> </li>
  <li> country: <%= @referee.country %> </li>
</ul>

<ul>
  <li> <%= link_to "Edit", edit_referee_path(@referee) %> </li>
  <li> <%= link_to "Destroy", referee_path(@referee),
    method: :delete,
    data: { confirm: 'Are you sure?' } %> </li>
</ul>